# Generated by Django 3.1.7 on 2021-03-21 16:38

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
