# Generated by Django 3.1.7 on 2021-03-21 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_from', models.DateTimeField(auto_now_add=True)),
                ('mod_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_for', to=settings.AUTH_USER_MODEL)),
                ('my_mods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_mods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mod_for', 'my_mods')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_from', models.DateTimeField(auto_now_add=True)),
                ('user_followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Followers', to=settings.AUTH_USER_MODEL)),
                ('user_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_following', 'user_followers')},
            },
        ),
    ]
