# Generated by Django 3.1.7 on 2021-03-21 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userfollow_usermodding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollow',
            old_name='follow_from',
            new_name='followed_at',
        ),
        migrations.RenameField(
            model_name='usermodding',
            old_name='mod_from',
            new_name='modded_at',
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('block_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_user', to=settings.AUTH_USER_MODEL)),
                ('blocked_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('block_user', 'blocked_from')},
            },
        ),
    ]
