# Generated by Django 3.1.7 on 2021-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210321_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_bio',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
