# Generated by Django 3.1.7 on 2021-04-07 08:28

from django.db import migrations, models
import myUsers.models


class Migration(migrations.Migration):

    dependencies = [
        ('myUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_icon',
            field=models.ImageField(default='default_user.jpeg', upload_to=myUsers.models.user_icon_path, verbose_name='User icon'),
        ),
    ]
